### ISSUE TITLE
Mime.to_string() does not match webidl patterns

### ISSUE THREAD

**Issue by jaysonsantos** [hyperium/mime.rs#41]
Hi I am implementing a PR on servo and I am using mime to sned conten-type to xhr.send and apparently `Mime.to_string()` is returning i.e. `text/html; charset=utf8` and mozilla's WebIDL expect it to be `text/html;charset=UTF-8`.
Could/should that be changed? If yes, let me know that I send a PR.

**Comment by seanmonstar** [comment]
The tests are incorrect. Both of those strings are considered equivalent, according to the spec: https://tools.ietf.org/html/rfc7231#section-3.1.1.1

**Comment by jaysonsantos** [comment]
Thanks @seanmonstar !
